
    version: 0.2
    phases:
      install:
        commands:
          - echo Setting up package manager and installing kubectl...
          - apt-get update
          - apt-get install -y apt-transport-https ca-certificates curl gnupg
          - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
          - sed -i 's/kubernetes-xenial/jammy/g' /etc/apt/sources.list.d/kubernetes.list  # Replace xenial with jammy
          - apt-get install -y kubectl
      pre_build:
        commands:
          - echo Logging in to Amazon ECR...
          - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      build:
        commands:
          - echo Build started...
          - docker build -t $IMAGE_REPO_NAME .
          - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      post_build:
        commands:
          - echo Pushing to ECR...
          - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
          - printf '[{"name":"brain-tasks","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest > imagedefinitions.json
          - echo Deploying to EKS...
          - aws eks update-kubeconfig --name brain-tasks-cluster --region $AWS_DEFAULT_REGION
          - kubectl apply -f deployment.yaml
          - kubectl apply -f service.yaml
