version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 253490797549.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t brain-tasks-app:latest .
      - docker tag brain-tasks-app:latest 253490797549.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 253490797549.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest
      - printf "[{\"name\":\"brain-tasks\",\"imageUri\":\"%s\"}]" 253490797549.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
